version: "3.9"
services:
  hummingbot:
    container_name: hummingbot1
    # image: rakd/hummingbot2:latest
    image: rakd/hummingbot2:latest
    # image: hummingbot/hummingbot:latest
#    build: Uncomment this and comment image if you want to build it locally
#      context: .
#      dockerfile: Dockerfile
    volumes:
      # - ./conf:/home/hummingbot/conf
      # - ./conf/connectors:/home/hummingbot/conf/connectors
      # - ./conf/strategies:/home/hummingbot/conf/strategies
      # - ./conf/controllers:/home/hummingbot/conf/controllers
      # - ./conf/scripts:/home/hummingbot/conf/scripts
      # - ./logs:/home/hummingbot/logs
      # - ./data:/home/hummingbot/data
      # - ./certs:/home/hummingbot/certs
      # - ./scripts:/home/hummingbot/scripts
      # - ./controllers:/home/hummingbot/controllers

      - "./hummingbot_files1/conf:/home/hummingbot/conf"
      - "./hummingbot_files1/conf/connectors:/home/hummingbot/conf/connectors"
      - "./hummingbot_files1/conf/strategies:/home/hummingbot/conf/strategies"
      - "./hummingbot_files1/logs:/home/hummingbot/logs"
      - "./hummingbot_files1/data:/home/hummingbot/data"
      - "./hummingbot_files1/scripts:/home/hummingbot/scripts"
      - "./certs:/home/hummingbot/certs"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    #  environment:
    #    - CONFIG_PASSWORD=a
    #    - CONFIG_FILE_NAME=simple_pmm_example.py
    #    - SCRIPT_CONFIG=conf_simple_pmm_example.yaml


  hummingbot2:
    container_name: hummingbot2
    image: hummingbot/hummingbot:latest
    volumes:
      - "./hummingbot_files2/conf:/home/hummingbot/conf"
      - "./hummingbot_files2/conf/connectors:/home/hummingbot/conf/connectors"
      - "./hummingbot_files2/conf/strategies:/home/hummingbot/conf/strategies"
      - "./hummingbot_files2/logs:/home/hummingbot/logs"
      - "./hummingbot_files2/data:/home/hummingbot/data"
      - "./hummingbot_files2/scripts:/home/hummingbot/scripts"
      # - "./hummingbot_files/certs:/home/hummingbot/certs"
      - "./certs:/home/hummingbot/certs"
    # environment:
    #   - CONFIG_PASSWORD=a
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host

  gateway:
   container_name: gateway
   image: rakd/hummingbot-gateway:latest
   ports:
     - "15888:15888"
     - "8080:8080"
   volumes:
     - "./gateway_files/conf:/home/gateway/conf"
     - "./gateway_files/logs:/home/gateway/logs"
     - "./gateway_files/db:/home/gateway/db"
     - "./certs:/home/gateway/certs"
   environment:
     - GATEWAY_PASSPHRASE=a
